<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="14" total="40" passed="0" failed="1" skipped="25">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-06-03T11:10:57Z" name="ARC Essential Test Suite " finished-at="2021-06-03T11:11:59Z" duration-ms="61664">
    <groups>
      <group name="LoginMethodTCGroup">
        <method signature="LoginPageTest.Login_ApplicationTest()[pri:1, instance:com.arc.testCases.LoginPageTest@12aba8be]" name="Login_ApplicationTest" class="com.arc.testCases.LoginPageTest"/>
      </group> <!-- LoginMethodTCGroup -->
    </groups>
    <test started-at="2021-06-03T11:10:57Z" name="ARC_Reboot_Test_Chrome " finished-at="2021-06-03T11:11:59Z" duration-ms="61664">
      <class name="com.arc.testCases.Project.BuildingPageTest">
        <test-method signature="Building_Agreement_Display()[pri:4, instance:com.arc.testCases.Project.BuildingPageTest@27462a88]" started-at="2021-06-03T16:41:59Z" name="Building_Agreement_Display" depends-on-groups="LoginMethodTCGroup" finished-at="2021-06-03T16:41:59Z" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method BuildingPageTest.Building_Agreement_Display()[pri:4, instance:com.arc.testCases.Project.BuildingPageTest@27462a88] depends on not successfully finished methods in group "LoginMethodTCGroup"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method BuildingPageTest.Building_Agreement_Display()[pri:4, instance:com.arc.testCases.Project.BuildingPageTest@27462a88] depends on not successfully finished methods in group "LoginMethodTCGroup"
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Building_Agreement_Display -->
        <test-method signature="Building_LEEDIDProject_Download_Invoice()[pri:4, instance:com.arc.testCases.Project.BuildingPageTest@27462a88]" started-at="2021-06-03T16:41:59Z" name="Building_LEEDIDProject_Download_Invoice" depends-on-groups="LoginMethodTCGroup" finished-at="2021-06-03T16:41:59Z" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method BuildingPageTest.Building_LEEDIDProject_Download_Invoice()[pri:4, instance:com.arc.testCases.Project.BuildingPageTest@27462a88] depends on not successfully finished methods in group "LoginMethodTCGroup"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method BuildingPageTest.Building_LEEDIDProject_Download_Invoice()[pri:4, instance:com.arc.testCases.Project.BuildingPageTest@27462a88] depends on not successfully finished methods in group "LoginMethodTCGroup"
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Building_LEEDIDProject_Download_Invoice -->
        <test-method signature="Building_PerformanceCertificate_Download_Invoice_Receipt()[pri:4, instance:com.arc.testCases.Project.BuildingPageTest@27462a88]" started-at="2021-06-03T16:41:59Z" name="Building_PerformanceCertificate_Download_Invoice_Receipt" depends-on-groups="LoginMethodTCGroup" finished-at="2021-06-03T16:41:59Z" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method BuildingPageTest.Building_PerformanceCertificate_Download_Invoice_Receipt()[pri:4, instance:com.arc.testCases.Project.BuildingPageTest@27462a88] depends on not successfully finished methods in group "LoginMethodTCGroup"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method BuildingPageTest.Building_PerformanceCertificate_Download_Invoice_Receipt()[pri:4, instance:com.arc.testCases.Project.BuildingPageTest@27462a88] depends on not successfully finished methods in group "LoginMethodTCGroup"
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Building_PerformanceCertificate_Download_Invoice_Receipt -->
        <test-method signature="Building_Recertification_Download_Invoice()[pri:4, instance:com.arc.testCases.Project.BuildingPageTest@27462a88]" started-at="2021-06-03T16:41:59Z" name="Building_Recertification_Download_Invoice" depends-on-groups="LoginMethodTCGroup" finished-at="2021-06-03T16:41:59Z" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method BuildingPageTest.Building_Recertification_Download_Invoice()[pri:4, instance:com.arc.testCases.Project.BuildingPageTest@27462a88] depends on not successfully finished methods in group "LoginMethodTCGroup"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method BuildingPageTest.Building_Recertification_Download_Invoice()[pri:4, instance:com.arc.testCases.Project.BuildingPageTest@27462a88] depends on not successfully finished methods in group "LoginMethodTCGroup"
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Building_Recertification_Download_Invoice -->
        <test-method signature="Building_Agreement_Download()[pri:4, instance:com.arc.testCases.Project.BuildingPageTest@27462a88]" started-at="2021-06-03T16:41:59Z" name="Building_Agreement_Download" depends-on-groups="LoginMethodTCGroup" finished-at="2021-06-03T16:41:59Z" depends-on-methods="com.arc.testCases.Project.BuildingPageTest.Building_Agreement_Display" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method BuildingPageTest.Building_Agreement_Download()[pri:4, instance:com.arc.testCases.Project.BuildingPageTest@27462a88] depends on not successfully finished methods in group "LoginMethodTCGroup"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method BuildingPageTest.Building_Agreement_Download()[pri:4, instance:com.arc.testCases.Project.BuildingPageTest@27462a88] depends on not successfully finished methods in group "LoginMethodTCGroup"
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Building_Agreement_Download -->
      </class> <!-- com.arc.testCases.Project.BuildingPageTest -->
      <class name="com.arc.testCases.Project.ParkingPageTest">
        <test-method signature="Parking_Agreement_Display()[pri:9, instance:com.arc.testCases.Project.ParkingPageTest@54a7079e]" started-at="2021-06-03T16:41:59Z" name="Parking_Agreement_Display" depends-on-groups="LoginMethodTCGroup" finished-at="2021-06-03T16:41:59Z" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method ParkingPageTest.Parking_Agreement_Display()[pri:9, instance:com.arc.testCases.Project.ParkingPageTest@54a7079e] depends on not successfully finished methods in group "LoginMethodTCGroup"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method ParkingPageTest.Parking_Agreement_Display()[pri:9, instance:com.arc.testCases.Project.ParkingPageTest@54a7079e] depends on not successfully finished methods in group "LoginMethodTCGroup"
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Parking_Agreement_Display -->
        <test-method signature="Parking_LEEDID_Project_Download_Invoice()[pri:9, instance:com.arc.testCases.Project.ParkingPageTest@54a7079e]" started-at="2021-06-03T16:41:59Z" name="Parking_LEEDID_Project_Download_Invoice" depends-on-groups="LoginMethodTCGroup" finished-at="2021-06-03T16:41:59Z" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method ParkingPageTest.Parking_LEEDID_Project_Download_Invoice()[pri:9, instance:com.arc.testCases.Project.ParkingPageTest@54a7079e] depends on not successfully finished methods in group "LoginMethodTCGroup"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method ParkingPageTest.Parking_LEEDID_Project_Download_Invoice()[pri:9, instance:com.arc.testCases.Project.ParkingPageTest@54a7079e] depends on not successfully finished methods in group "LoginMethodTCGroup"
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Parking_LEEDID_Project_Download_Invoice -->
        <test-method signature="Parking_Agreement_Download()[pri:9, instance:com.arc.testCases.Project.ParkingPageTest@54a7079e]" started-at="2021-06-03T16:41:59Z" name="Parking_Agreement_Download" depends-on-groups="LoginMethodTCGroup" finished-at="2021-06-03T16:41:59Z" depends-on-methods="com.arc.testCases.Project.ParkingPageTest.Parking_Agreement_Display" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method ParkingPageTest.Parking_Agreement_Download()[pri:9, instance:com.arc.testCases.Project.ParkingPageTest@54a7079e] depends on not successfully finished methods in group "LoginMethodTCGroup"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method ParkingPageTest.Parking_Agreement_Download()[pri:9, instance:com.arc.testCases.Project.ParkingPageTest@54a7079e] depends on not successfully finished methods in group "LoginMethodTCGroup"
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Parking_Agreement_Download -->
      </class> <!-- com.arc.testCases.Project.ParkingPageTest -->
      <class name="com.arc.testCases.Project.SchoolPageTest">
        <test-method signature="School_Agreement_Display()[pri:5, instance:com.arc.testCases.Project.SchoolPageTest@659499f1]" started-at="2021-06-03T16:41:59Z" name="School_Agreement_Display" depends-on-groups="LoginMethodTCGroup" finished-at="2021-06-03T16:41:59Z" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method SchoolPageTest.School_Agreement_Display()[pri:5, instance:com.arc.testCases.Project.SchoolPageTest@659499f1] depends on not successfully finished methods in group "LoginMethodTCGroup"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method SchoolPageTest.School_Agreement_Display()[pri:5, instance:com.arc.testCases.Project.SchoolPageTest@659499f1] depends on not successfully finished methods in group "LoginMethodTCGroup"
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- School_Agreement_Display -->
        <test-method signature="School_LEEDProject_DownloadInvoice()[pri:5, instance:com.arc.testCases.Project.SchoolPageTest@659499f1]" started-at="2021-06-03T16:41:59Z" name="School_LEEDProject_DownloadInvoice" depends-on-groups="LoginMethodTCGroup" finished-at="2021-06-03T16:41:59Z" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method SchoolPageTest.School_LEEDProject_DownloadInvoice()[pri:5, instance:com.arc.testCases.Project.SchoolPageTest@659499f1] depends on not successfully finished methods in group "LoginMethodTCGroup"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method SchoolPageTest.School_LEEDProject_DownloadInvoice()[pri:5, instance:com.arc.testCases.Project.SchoolPageTest@659499f1] depends on not successfully finished methods in group "LoginMethodTCGroup"
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- School_LEEDProject_DownloadInvoice -->
        <test-method signature="School_PerformanceCertificate_Download_Invoice_Receipt()[pri:5, instance:com.arc.testCases.Project.SchoolPageTest@659499f1]" started-at="2021-06-03T16:41:59Z" name="School_PerformanceCertificate_Download_Invoice_Receipt" depends-on-groups="LoginMethodTCGroup" finished-at="2021-06-03T16:41:59Z" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method SchoolPageTest.School_PerformanceCertificate_Download_Invoice_Receipt()[pri:5, instance:com.arc.testCases.Project.SchoolPageTest@659499f1] depends on not successfully finished methods in group "LoginMethodTCGroup"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method SchoolPageTest.School_PerformanceCertificate_Download_Invoice_Receipt()[pri:5, instance:com.arc.testCases.Project.SchoolPageTest@659499f1] depends on not successfully finished methods in group "LoginMethodTCGroup"
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- School_PerformanceCertificate_Download_Invoice_Receipt -->
        <test-method signature="School_Agreement_Download()[pri:5, instance:com.arc.testCases.Project.SchoolPageTest@659499f1]" started-at="2021-06-03T16:41:59Z" name="School_Agreement_Download" depends-on-groups="LoginMethodTCGroup" finished-at="2021-06-03T16:41:59Z" depends-on-methods="com.arc.testCases.Project.SchoolPageTest.School_Agreement_Display" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method SchoolPageTest.School_Agreement_Download()[pri:5, instance:com.arc.testCases.Project.SchoolPageTest@659499f1] depends on not successfully finished methods in group "LoginMethodTCGroup"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method SchoolPageTest.School_Agreement_Download()[pri:5, instance:com.arc.testCases.Project.SchoolPageTest@659499f1] depends on not successfully finished methods in group "LoginMethodTCGroup"
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- School_Agreement_Download -->
      </class> <!-- com.arc.testCases.Project.SchoolPageTest -->
      <class name="com.arc.testCases.Project.TransitPageTest">
        <test-method signature="Transit_Agreement_Display()[pri:7, instance:com.arc.testCases.Project.TransitPageTest@47e2e487]" started-at="2021-06-03T16:41:59Z" name="Transit_Agreement_Display" depends-on-groups="LoginMethodTCGroup" finished-at="2021-06-03T16:41:59Z" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TransitPageTest.Transit_Agreement_Display()[pri:7, instance:com.arc.testCases.Project.TransitPageTest@47e2e487] depends on not successfully finished methods in group "LoginMethodTCGroup"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TransitPageTest.Transit_Agreement_Display()[pri:7, instance:com.arc.testCases.Project.TransitPageTest@47e2e487] depends on not successfully finished methods in group "LoginMethodTCGroup"
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Transit_Agreement_Display -->
        <test-method signature="Transit_CreditForm_Download_Upload_Document()[pri:7, instance:com.arc.testCases.Project.TransitPageTest@47e2e487]" started-at="2021-06-03T16:41:59Z" name="Transit_CreditForm_Download_Upload_Document" depends-on-groups="LoginMethodTCGroup" finished-at="2021-06-03T16:41:59Z" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TransitPageTest.Transit_CreditForm_Download_Upload_Document()[pri:7, instance:com.arc.testCases.Project.TransitPageTest@47e2e487] depends on not successfully finished methods in group "LoginMethodTCGroup"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TransitPageTest.Transit_CreditForm_Download_Upload_Document()[pri:7, instance:com.arc.testCases.Project.TransitPageTest@47e2e487] depends on not successfully finished methods in group "LoginMethodTCGroup"
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Transit_CreditForm_Download_Upload_Document -->
        <test-method signature="Transit_File_Upload_Remove()[pri:7, instance:com.arc.testCases.Project.TransitPageTest@47e2e487]" started-at="2021-06-03T16:41:59Z" name="Transit_File_Upload_Remove" depends-on-groups="LoginMethodTCGroup" finished-at="2021-06-03T16:41:59Z" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TransitPageTest.Transit_File_Upload_Remove()[pri:7, instance:com.arc.testCases.Project.TransitPageTest@47e2e487] depends on not successfully finished methods in group "LoginMethodTCGroup"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TransitPageTest.Transit_File_Upload_Remove()[pri:7, instance:com.arc.testCases.Project.TransitPageTest@47e2e487] depends on not successfully finished methods in group "LoginMethodTCGroup"
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Transit_File_Upload_Remove -->
        <test-method signature="Transit_LEEDIDProject_Download_Invoice()[pri:7, instance:com.arc.testCases.Project.TransitPageTest@47e2e487]" started-at="2021-06-03T16:41:59Z" name="Transit_LEEDIDProject_Download_Invoice" depends-on-groups="LoginMethodTCGroup" finished-at="2021-06-03T16:41:59Z" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TransitPageTest.Transit_LEEDIDProject_Download_Invoice()[pri:7, instance:com.arc.testCases.Project.TransitPageTest@47e2e487] depends on not successfully finished methods in group "LoginMethodTCGroup"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TransitPageTest.Transit_LEEDIDProject_Download_Invoice()[pri:7, instance:com.arc.testCases.Project.TransitPageTest@47e2e487] depends on not successfully finished methods in group "LoginMethodTCGroup"
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Transit_LEEDIDProject_Download_Invoice -->
        <test-method signature="Transit_Agreement_Download()[pri:7, instance:com.arc.testCases.Project.TransitPageTest@47e2e487]" started-at="2021-06-03T16:41:59Z" name="Transit_Agreement_Download" depends-on-groups="LoginMethodTCGroup" finished-at="2021-06-03T16:41:59Z" depends-on-methods="com.arc.testCases.Project.TransitPageTest.Transit_Agreement_Display" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TransitPageTest.Transit_Agreement_Download()[pri:7, instance:com.arc.testCases.Project.TransitPageTest@47e2e487] depends on not successfully finished methods in group "LoginMethodTCGroup"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TransitPageTest.Transit_Agreement_Download()[pri:7, instance:com.arc.testCases.Project.TransitPageTest@47e2e487] depends on not successfully finished methods in group "LoginMethodTCGroup"
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Transit_Agreement_Download -->
      </class> <!-- com.arc.testCases.Project.TransitPageTest -->
      <class name="com.arc.testCases.Project.CommunitiesPageTest">
        <test-method signature="Communities_Agreement_Display()[pri:8, instance:com.arc.testCases.Project.CommunitiesPageTest@61001b64]" started-at="2021-06-03T16:41:59Z" name="Communities_Agreement_Display" depends-on-groups="LoginMethodTCGroup" finished-at="2021-06-03T16:41:59Z" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method CommunitiesPageTest.Communities_Agreement_Display()[pri:8, instance:com.arc.testCases.Project.CommunitiesPageTest@61001b64] depends on not successfully finished methods in group "LoginMethodTCGroup"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method CommunitiesPageTest.Communities_Agreement_Display()[pri:8, instance:com.arc.testCases.Project.CommunitiesPageTest@61001b64] depends on not successfully finished methods in group "LoginMethodTCGroup"
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Communities_Agreement_Display -->
        <test-method signature="Community_LEEDIDProject_Download_Invoice()[pri:8, instance:com.arc.testCases.Project.CommunitiesPageTest@61001b64]" started-at="2021-06-03T16:41:59Z" name="Community_LEEDIDProject_Download_Invoice" depends-on-groups="LoginMethodTCGroup" finished-at="2021-06-03T16:41:59Z" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method CommunitiesPageTest.Community_LEEDIDProject_Download_Invoice()[pri:8, instance:com.arc.testCases.Project.CommunitiesPageTest@61001b64] depends on not successfully finished methods in group "LoginMethodTCGroup"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method CommunitiesPageTest.Community_LEEDIDProject_Download_Invoice()[pri:8, instance:com.arc.testCases.Project.CommunitiesPageTest@61001b64] depends on not successfully finished methods in group "LoginMethodTCGroup"
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Community_LEEDIDProject_Download_Invoice -->
        <test-method signature="Communities_Agreement_Download()[pri:8, instance:com.arc.testCases.Project.CommunitiesPageTest@61001b64]" started-at="2021-06-03T16:41:59Z" name="Communities_Agreement_Download" depends-on-groups="LoginMethodTCGroup" finished-at="2021-06-03T16:41:59Z" depends-on-methods="com.arc.testCases.Project.CommunitiesPageTest.Communities_Agreement_Display" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method CommunitiesPageTest.Communities_Agreement_Download()[pri:8, instance:com.arc.testCases.Project.CommunitiesPageTest@61001b64] depends on not successfully finished methods in group "LoginMethodTCGroup"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method CommunitiesPageTest.Communities_Agreement_Download()[pri:8, instance:com.arc.testCases.Project.CommunitiesPageTest@61001b64] depends on not successfully finished methods in group "LoginMethodTCGroup"
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Communities_Agreement_Download -->
      </class> <!-- com.arc.testCases.Project.CommunitiesPageTest -->
      <class name="com.arc.testCases.LoginPageTest">
        <test-method is-config="true" signature="initializtion(java.lang.String)[pri:0, instance:com.arc.testCases.LoginPageTest@12aba8be]" started-at="2021-06-03T16:40:58Z" name="initializtion" finished-at="2021-06-03T16:41:07Z" duration-ms="9871" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializtion -->
        <test-method signature="Login_ApplicationTest()[pri:1, instance:com.arc.testCases.LoginPageTest@12aba8be]" started-at="2021-06-03T16:41:07Z" name="Login_ApplicationTest" finished-at="2021-06-03T16:41:59Z" duration-ms="51355" status="FAIL">
          <exception class="org.openqa.selenium.InvalidSelectorException">
            <message>
              <![CDATA[invalid selector: Unable to locate an element with the xpath expression //body/div[@id='app']/div[1]/div[1]/form[1]/div[7]/input[1]1 because of the following error:
SyntaxError: Failed to execute 'evaluate' on 'Document': The string '//body/div[@id='app']/div[1]/div[1]/form[1]/div[7]/input[1]1' is not a valid XPath expression.
  (Session info: chrome=91.0.4472.77)
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/invalid_selector_exception.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'G10GGNLT065', ip: '192.168.43.9', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '15.0.2'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 91.0.4472.77, chrome: {chromedriverVersion: 90.0.4430.24 (4c6d850f087da..., userDataDir: C:\Users\NARAYA~1\AppData\L...}, goog:chromeOptions: {debuggerAddress: localhost:62336}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: c000ae7962acf8302930a811c7eb5f8e
*** Element info: {Using=xpath, value=//body/div[@id='app']/div[1]/div[1]/form[1]/div[7]/input[1]1}]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.InvalidSelectorException: invalid selector: Unable to locate an element with the xpath expression //body/div[@id='app']/div[1]/div[1]/form[1]/div[7]/input[1]1 because of the following error:
SyntaxError: Failed to execute 'evaluate' on 'Document': The string '//body/div[@id='app']/div[1]/div[1]/form[1]/div[7]/input[1]1' is not a valid XPath expression.
  (Session info: chrome=91.0.4472.77)
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/invalid_selector_exception.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'G10GGNLT065', ip: '192.168.43.9', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '15.0.2'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 91.0.4472.77, chrome: {chromedriverVersion: 90.0.4430.24 (4c6d850f087da..., userDataDir: C:\Users\NARAYA~1\AppData\L...}, goog:chromeOptions: {debuggerAddress: localhost:62336}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: c000ae7962acf8302930a811c7eb5f8e
*** Element info: {Using=xpath, value=//body/div[@id='app']/div[1]/div[1]/form[1]/div[7]/input[1]1}
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:323)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:428)
	at org.openqa.selenium.By$ByXPath.findElement(By.java:353)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:315)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.openqa.selenium.support.events.EventFiringWebDriver.lambda$new$1(EventFiringWebDriver.java:105)
	at com.sun.proxy.$Proxy11.findElement(Unknown Source)
	at org.openqa.selenium.support.events.EventFiringWebDriver.findElement(EventFiringWebDriver.java:194)
	at org.openqa.selenium.support.pagefactory.DefaultElementLocator.findElement(DefaultElementLocator.java:69)
	at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:38)
	at com.sun.proxy.$Proxy15.sendKeys(Unknown Source)
	at com.arc.PageObject.LoginPageObjects.login(LoginPageObjects.java:50)
	at com.arc.testCases.LoginPageTest.Login_ApplicationTest(LoginPageTest.java:53)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.InvalidSelectorException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login_ApplicationTest -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:com.arc.testCases.LoginPageTest@12aba8be]" started-at="2021-06-03T16:41:59Z" name="closeBrowser" finished-at="2021-06-03T16:41:59Z" duration-ms="84" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- com.arc.testCases.LoginPageTest -->
      <class name="com.arc.testCases.Project.CityPageTest">
        <test-method signature="City_Agreement_Display()[pri:6, instance:com.arc.testCases.Project.CityPageTest@51e69659]" started-at="2021-06-03T16:41:59Z" name="City_Agreement_Display" depends-on-groups="LoginMethodTCGroup" finished-at="2021-06-03T16:41:59Z" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method CityPageTest.City_Agreement_Display()[pri:6, instance:com.arc.testCases.Project.CityPageTest@51e69659] depends on not successfully finished methods in group "LoginMethodTCGroup"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method CityPageTest.City_Agreement_Display()[pri:6, instance:com.arc.testCases.Project.CityPageTest@51e69659] depends on not successfully finished methods in group "LoginMethodTCGroup"
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- City_Agreement_Display -->
        <test-method signature="City_LEEDIDProject_Download_Invoice()[pri:6, instance:com.arc.testCases.Project.CityPageTest@51e69659]" started-at="2021-06-03T16:41:59Z" name="City_LEEDIDProject_Download_Invoice" depends-on-groups="LoginMethodTCGroup" finished-at="2021-06-03T16:41:59Z" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method CityPageTest.City_LEEDIDProject_Download_Invoice()[pri:6, instance:com.arc.testCases.Project.CityPageTest@51e69659] depends on not successfully finished methods in group "LoginMethodTCGroup"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method CityPageTest.City_LEEDIDProject_Download_Invoice()[pri:6, instance:com.arc.testCases.Project.CityPageTest@51e69659] depends on not successfully finished methods in group "LoginMethodTCGroup"
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- City_LEEDIDProject_Download_Invoice -->
        <test-method signature="City_Agreement_Download()[pri:6, instance:com.arc.testCases.Project.CityPageTest@51e69659]" started-at="2021-06-03T16:41:59Z" name="City_Agreement_Download" depends-on-groups="LoginMethodTCGroup" finished-at="2021-06-03T16:41:59Z" depends-on-methods="com.arc.testCases.Project.CityPageTest.City_Agreement_Display" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method CityPageTest.City_Agreement_Download()[pri:6, instance:com.arc.testCases.Project.CityPageTest@51e69659] depends on not successfully finished methods in group "LoginMethodTCGroup"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method CityPageTest.City_Agreement_Download()[pri:6, instance:com.arc.testCases.Project.CityPageTest@51e69659] depends on not successfully finished methods in group "LoginMethodTCGroup"
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- City_Agreement_Download -->
      </class> <!-- com.arc.testCases.Project.CityPageTest -->
      <class name="com.arc.testCases.HomePageTest">
        <test-method signature="EssentialUser_Download_Invoice()[pri:2, instance:com.arc.testCases.HomePageTest@290222c1]" started-at="2021-06-03T16:41:59Z" name="EssentialUser_Download_Invoice" depends-on-groups="LoginMethodTCGroup" finished-at="2021-06-03T16:41:59Z" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method HomePageTest.EssentialUser_Download_Invoice()[pri:2, instance:com.arc.testCases.HomePageTest@290222c1] depends on not successfully finished methods in group "LoginMethodTCGroup"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method HomePageTest.EssentialUser_Download_Invoice()[pri:2, instance:com.arc.testCases.HomePageTest@290222c1] depends on not successfully finished methods in group "LoginMethodTCGroup"
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- EssentialUser_Download_Invoice -->
        <test-method signature="Logout_Test()[pri:100, instance:com.arc.testCases.HomePageTest@290222c1]" started-at="2021-06-03T16:41:59Z" name="Logout_Test" depends-on-groups="LoginMethodTCGroup" finished-at="2021-06-03T16:41:59Z" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method HomePageTest.Logout_Test()[pri:100, instance:com.arc.testCases.HomePageTest@290222c1] depends on not successfully finished methods in group "LoginMethodTCGroup"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method HomePageTest.Logout_Test()[pri:100, instance:com.arc.testCases.HomePageTest@290222c1] depends on not successfully finished methods in group "LoginMethodTCGroup"
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Logout_Test -->
      </class> <!-- com.arc.testCases.HomePageTest -->
    </test> <!-- ARC_Reboot_Test_Chrome  -->
  </suite> <!-- ARC Essential Test Suite  -->
</testng-results>
